#!/bin/sh
# Drop optional IDE marketing / co-author trailers from commit messages.
# Enable: git config core.hooksPath .githooks
msg="$1"
[ -f "$msg" ] || exit 0
tmp="${msg}.$$"
awk '
/^[[:space:]]*[Mm]ade-with:[[:space:]]*[Cc]ursor[[:space:]]*$/ { next }
/^[[:space:]]*[Mm]ade with [Cc]ursor[[:space:]]*$/ { next }
/^[[:space:]]*Co-authored-by:[[:space:]]*Cursor[[:space:]]*<cursoragent@cursor.com>[[:space:]]*$/ { next }
{ print }
' "$msg" > "$tmp" && mv "$tmp" "$msg"
